services:
    my_service:
        type: "service"
        command: "./service.sh"
        state:
            log:
                ready: "Service is ready"
    my_action:
        type: "action"
        command: "./action.sh"
        dependency:
            items:
                my_service: "ready"
output:
    state_times: "state_transition_times.json"
max_run_time: 60
